// Name: Gabriel Ginsberg
// Email: gginsber@bu.edu
// Description: Root layout for the financial-tracker mobile app.
//              Wraps every screen in the AuthProvider so any descendant
//              can call useAuth(); registers the (auth) and (tabs) route
//              groups; and runs the auth gate that redirects unauthenticated
//              users to /login and authenticated users away from the auth
//              group when they navigate back.

import FontAwesome from '@expo/vector-icons/FontAwesome';
import { DarkTheme, DefaultTheme, ThemeProvider } from '@react-navigation/native';
import { useFonts } from 'expo-font';
import { Stack, useRouter, useSegments } from 'expo-router';
import * as SplashScreen from 'expo-splash-screen';
import { useEffect } from 'react';
import { ActivityIndicator, View } from 'react-native';
import 'react-native-reanimated';

import { useColorScheme } from '@/components/useColorScheme';
import { AuthProvider, useAuth } from '@/src/auth/AuthContext';

export {
  // Catch any errors thrown by the Layout component.
  ErrorBoundary,
} from 'expo-router';

// Prevent the splash screen from auto-hiding before asset loading is complete.
SplashScreen.preventAutoHideAsync();

export default function RootLayout() {
  const [loaded, error] = useFonts({
    SpaceMono: require('../assets/fonts/SpaceMono-Regular.ttf'),
    ...FontAwesome.font,
  });

  // Expo Router uses Error Boundaries to catch errors in the navigation tree.
  useEffect(() => {
    if (error) throw error;
  }, [error]);

  useEffect(() => {
    if (loaded) {
      SplashScreen.hideAsync();
    }
  }, [loaded]);

  if (!loaded) {
    return null;
  }

  return (
    <AuthProvider>
      <RootLayoutNav />
    </AuthProvider>
  );
}

/**
 * Inside-AuthProvider layout. Reads the current session and segment
 * group, then redirects to the matching tree:
 *   - anonymous + outside (auth) -> push to /login
 *   - authenticated + inside (auth) -> push to / (tabs)
 * While auth state is restoring from SecureStore, render a centered
 * spinner so neither tree flashes briefly.
 */
function RootLayoutNav() {
  const colorScheme = useColorScheme();
  const { session, isLoading } = useAuth();
  const segments = useSegments();
  const router = useRouter();

  useEffect(() => {
    if (isLoading) return;
    // The casts below work around the stale .expo/types cache which is
    // generated by expo-router and does not yet know about the (auth)
    // group. Running `npx expo start` regenerates the cache; the casts
    // can then be removed.
    const inAuthGroup = (segments[0] as string) === '(auth)';
    if (!session && !inAuthGroup) {
      router.replace('/(auth)/login' as never);
    } else if (session && inAuthGroup) {
      router.replace('/');
    }
  }, [isLoading, session, segments, router]);

  if (isLoading) {
    return (
      <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }}>
        <ActivityIndicator size="large" />
      </View>
    );
  }

  return (
    <ThemeProvider value={colorScheme === 'dark' ? DarkTheme : DefaultTheme}>
      <Stack>
        <Stack.Screen name="(auth)" options={{ headerShown: false }} />
        <Stack.Screen name="(tabs)" options={{ headerShown: false }} />
        <Stack.Screen name="modal" options={{ presentation: 'modal' }} />
      </Stack>
    </ThemeProvider>
  );
}
