# Generated by Django 6.0.3 on 2026-05-01 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0003_remove_personal_billings"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="paymentmethod",
            options={"ordering": ["nickname", "id"]},
        ),
        migrations.AddField(
            model_name="recurringexpense",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="recurringexpense",
            name="payment_url",
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
