# Generated by Django 6.0.1 on 2026-03-02 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mini_insta", "0002_post_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="image_file",
            field=models.ImageField(blank=True, upload_to="photos/"),
        ),
        migrations.AlterField(
            model_name="photo",
            name="image_url",
            field=models.URLField(blank=True),
        ),
    ]
