# Generated by Django 6.0.1 on 2026-03-05 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mini_insta", "0005_profile_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="profile_image_file",
            field=models.ImageField(blank=True, upload_to="profile_images/"),
        ),
    ]
