# Name: Gabriel Ginsberg
# Email: gginsber@bu.edu
# Description: URL configuration for the project app. Mounts the DRF router
#              that exposes the financial-tracker REST API under
#              /project/api/, plus explicit paths for the singleton profile
#              endpoint, the price-increase report, and the token-issuance
#              endpoint used by the React Native client. Web (template-based)
#              ListView/DetailView routes are added in Phase 3.

from django.contrib.auth import views as auth_views
from django.urls import include, path
from rest_framework.routers import DefaultRouter

from . import views

app_name = "project"


# DRF router for the user-owned and read-only resource ViewSets. The router
# auto-generates standard CRUD URLs (list, retrieve, create, update, destroy)
# and also wires up the @action methods declared on the ViewSets — including
# the nested price-history list described in DESIGN.md §5.1.
api_router = DefaultRouter()
api_router.register(r"categories", views.CategoryViewSet, basename="category")
api_router.register(r"payment-methods", views.PaymentMethodViewSet, basename="paymentmethod")
api_router.register(r"expenses", views.RecurringExpenseViewSet, basename="expense")
api_router.register(r"price-history", views.PriceHistoryViewSet, basename="pricehistory")


urlpatterns = [
    # ---- Web frontend (Phase 3 minimum-viable) ------------------------------
    path("", views.LandingView.as_view(), name="landing"),

    # Auth: Django's built-in CBVs with project-namespaced templates.
    path(
        "login/",
        auth_views.LoginView.as_view(template_name="project/login.html"),
        name="login",
    ),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),

    # Per-model ListView + DetailView (rubric §9.5; per-user filtering
    # enforced inside each view's get_queryset).
    path("profiles/", views.UserProfileListView.as_view(), name="profile_list"),
    path("profiles/<int:pk>/", views.UserProfileDetailView.as_view(), name="profile_detail"),

    path("categories/", views.CategoryListView.as_view(), name="category_list"),
    path("categories/<int:pk>/", views.CategoryDetailView.as_view(), name="category_detail"),

    path("payment-methods/", views.PaymentMethodListView.as_view(), name="paymentmethod_list"),
    path(
        "payment-methods/<int:pk>/",
        views.PaymentMethodDetailView.as_view(),
        name="paymentmethod_detail",
    ),

    path("expenses/", views.RecurringExpenseListView.as_view(), name="expense_list"),
    path(
        "expenses/<int:pk>/",
        views.RecurringExpenseDetailView.as_view(),
        name="expense_detail",
    ),

    path("price-history/", views.PriceHistoryListView.as_view(), name="pricehistory_list"),
    path(
        "price-history/<int:pk>/",
        views.PriceHistoryDetailView.as_view(),
        name="pricehistory_detail",
    ),

    # ---- API ----------------------------------------------------------------
    # Singleton current-user profile. Mounted before the router include so
    # /api/profile/ does not collide with any future router path.
    path(
        "api/profile/",
        views.CurrentProfileView.as_view(),
        name="api_profile",
    ),
    # Cross-model derived report (DESIGN.md §9.6) — surfaces both
    # increases and decreases over the trailing window.
    path(
        "api/reports/price-changes/",
        views.price_change_report,
        name="api_price_change_report",
    ),
    # Sign-up (creates User + UserProfile atomically, returns a token so
    # the mobile client can treat sign-up as auto-login).
    path(
        "api/auth/register/",
        views.UserRegistrationView.as_view(),
        name="api_auth_register",
    ),
    # Login: token issuance for the React Native client.
    path(
        "api/auth/login/",
        views.FinanceTrackerObtainAuthToken.as_view(),
        name="api_auth_login",
    ),
    # Standard ViewSet CRUD routes generated by the router.
    path("api/", include(api_router.urls)),
]
